language: node_js
node_js:
  - 0.8

services: postgresql
before_script:
  - echo -e '\n\n\n\n\n\n\n\n' | make certs
  - psql -c 'create database openruko_test;' -U postgres
env: PG_USER=postgres PG_PASSWORD=
