#!/bin/bash

echo "Note: Must run from postgres/ directory"
echo "Shame: This script needs some serious TLC"
echo "Initial setup for a clean openruko database"
set -e
set -o pipefail

echo -en "\nDatabase name: "
read dbName

echo -n "Your name: "
read oruser_name
echo -n "Your email: "
read oruser_email
echo -n "Desired password: "
read -s oruser_password

# horrible, yucky

(psql --list | grep "^ $dbName ") || psql postgres -c "CREATE DATABASE $dbName;" > /dev/null

if [ -z $APISERVER_KEY ]; then
  superUserKey=$(uuidgen)
else
  superUserKey=$APISERVER_KEY
fi

psql "$dbName" -o /dev/null -nq -c "SET search_path TO openruko_data,public; SELECT * FROM openruko_api.add_user('$oruser_email','$oruser_name','$oruser_password')"
psql "$dbName" -o /dev/null -nq -c "SET search_path TO openruko_data,public; SELECT * FROM openruko_api.add_user('admin@dev.null','superuser','superuser', true, '$superUserKey')"
echo ""
echo "Note the following environment variable:"
echo "^^ (set this in gitmouth and dyno hosts' env vars - see README.md)"
echo "APISERVER_KEY=$superUserKey"

echo ""
echo "Database $dbName setup complete"
